site_name: Vahid Vahidinasab
site_author: Vahid Vahidinasab
site_url: https://vahidinasab.github.io/
theme:
  name: material
  icon:
    logo: material/contacts
  favicon: images/favicon.png
  palette:
    primary: purple
    accent: deep orange
  features:
    - navigation.instant
    - navigation.tabs
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/vahidinasab
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/seyed-amir-alavi/
markdown_extensions:
  - attr_list
plugins:
  - search # necessary for search to work

nav:
  - index.md
  - cv.md
  - activities.md
  - interests.md
  - publications.md
  - teaching.md
  - contact.md
  - Blog:
    - blog/blog.md
